#!/usr/bin/env bash

if [ $# -ne 1 ]; then
  echo "You did not input a 4 digit number"
  exit 1
fi

if [[ ! $1 =~ ^[0-9]{4}$ ]]; then
  echo "Error: Input must be a 4-digit integer."
  exit 1
fi

hash_value=$(echo -n "$1" | sha256sum | awk '{print $1}')

echo "$hash_value"
